services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: formcore-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@localhost}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      formcore-db:
        condition: service_healthy
    networks:
      - formcore-network
    restart: unless-stopped
